describe('Form', () => {
  beforeEach(() => {
    cy.intercept('GET', 'http://localhost:3001/api/v1/students', {fixture: "newStudents"})
    cy.intercept('POST', 'http://localhost:3001/api/v1/students', {fixture: "postStudent"})
    cy.visit('http://localhost:3000/students/form')
  })
  it('should render the form and show if the input is required or optional', () => {
    cy.get('[name="name"]')
    cy.get('form > :nth-child(2)')
    cy.get('[placeholder="Favorite Bands"]')
    cy.get('form > :nth-child(4)')
    cy.get('[placeholder="Favorite Foods"]')
    cy.get('form > :nth-child(6)')
    cy.get('[placeholder="Pets"]')
    cy.get('form > :nth-child(8)')
    cy.get('[placeholder="Location"]')
    cy.get('form > :nth-child(10)')
    cy.get('[placeholder="Image"]')
    cy.get('form > :nth-child(12)')
    cy.get('.submit-button')
  })
  it('should be able to fill out the form and see the data posted', () => {
    cy.get('[name="name"]').type('Dinne Kopelevich')
    cy.get('[name="name"]').should('have.value', 'Dinne Kopelevich')
    cy.get('[placeholder="Favorite Bands"]').type('Bat For Lashes')
    cy.get('[placeholder="Favorite Bands"]').should('have.value', 'Bat For Lashes')
    cy.get('[placeholder="Favorite Foods"]').type('Dumplings')
    cy.get('[placeholder="Favorite Foods"]').should('have.value', 'Dumplings')
    cy.get('[placeholder="Pets"]').type('None (yet)')
    cy.get('[placeholder="Pets"]').should('have.value', 'None (yet)')
    cy.get('[placeholder="Location"]').type('Denver, CO (for now)')
    cy.get('[placeholder="Location"]').should('have.value', 'Denver, CO (for now)')
    cy.get('[placeholder="Image"]').type('https://ca.slack-edge.com/T029P2S9M-U037D8A3JAF-9c447e33ba89-512')
    cy.get('[placeholder="Image"]').should('have.value', 'https://ca.slack-edge.com/T029P2S9M-U037D8A3JAF-9c447e33ba89-512')
    cy.get('.submit-button').click()
  })
})
